//! Embeds the `miao-server` payloads this dashboard carries, and nothing
//! else.
//!
//! `CM_SERVER_PAYLOAD_MANIFEST` names a TSV that `cargo xtask` writes —
//! `<target>\t<sha256>\t<path to .gz>` per line — and each archive is
//! `include_bytes!`d into `src/server_payload.rs`'s table. **Unset is the normal
//! case**: an ordinary `cargo build` embeds nothing, links nothing extra, and
//! honestly reports carrying no server.
//!
//! That environment variable *is* the switch, which is why there is no cargo
//! feature beside it. One switch, and it carries the payload with it.
//!
//! Note what this script does **not** do: it does not build, download, or decide
//! anything. Obtaining a server — cross-compiling it, fetching a released one,
//! taking a path — happens in `xtask`, which then hands the finished archives
//! over. Keeping that out of here is what lets a bundled build need no cross
//! toolchain and keeps `cargo build` / `clippy` / `check` identical either way.
//! See `docs/crate-split.md`.

use std::path::{Path, PathBuf};

/// The manifest naming what to embed. Written by `cargo xtask`.
const MANIFEST_ENV: &str = "CM_SERVER_PAYLOAD_MANIFEST";

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    // The variable itself, so a build re-runs when it appears, vanishes, or names
    // a different manifest. The manifest's *contents* — and each archive it names
    // — are watched separately, in `read_manifest` and the loop below, so that a
    // build carrying nothing watches nothing.
    println!("cargo::rerun-if-env-changed={MANIFEST_ENV}");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let entries = match std::env::var(MANIFEST_ENV) {
        Ok(path) if !path.trim().is_empty() => read_manifest(Path::new(path.trim())),
        _ => Vec::new(),
    };

    let mut generated = String::from(
        "// @generated by build.rs from the CM_SERVER_PAYLOAD_MANIFEST manifest.\n\
         pub(crate) static PAYLOADS: &[ServerPayload] = &[\n",
    );
    for (i, (target, sha256, gz)) in entries.iter().enumerate() {
        // Watch the archive where it actually lives, but embed a *copy* under
        // OUT_DIR. Embedding the watched file directly ties its mtime to the
        // build script's own stamp, and cargo then re-runs the script on every
        // build — a spurious recompile of the whole crate, every time.
        println!("cargo::rerun-if-changed={}", gz.display());
        let staged = out.join(format!("server-payload-{i}.gz"));
        std::fs::copy(gz, &staged)
            .unwrap_or_else(|e| panic!("copying {} to {}: {e}", gz.display(), staged.display()));
        generated.push_str(&format!(
            "    ServerPayload {{ target: {target:?}, sha256: {sha256:?}, \
             gz: include_bytes!({:?}) }},\n",
            staged.display().to_string()
        ));
    }
    generated.push_str("];\n");

    let dest = out.join("payloads.rs");
    std::fs::write(&dest, generated).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}

/// Parse the manifest, or die saying why.
///
/// Deliberately fatal rather than lenient. A manifest that is *set* and wrong is
/// always a mistake — a stale exported variable, or a bad hand-written line — and
/// the lenient reading would produce a dashboard that silently carries nothing
/// while every sign says it should. The quiet path is the variable being unset,
/// which never reaches here.
fn read_manifest(path: &Path) -> Vec<(String, String, PathBuf)> {
    println!("cargo::rerun-if-changed={}", path.display());
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!(
            "{MANIFEST_ENV} names {}, which cannot be read: {e}",
            path.display()
        )
    });

    let mut out = Vec::new();
    for (n, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let bad = |why: &str| -> ! {
            panic!("{}:{}: {why}\n  {line}", path.display(), n + 1);
        };
        let mut fields = line.split('\t');
        let (Some(target), Some(sha256), Some(gz), None) =
            (fields.next(), fields.next(), fields.next(), fields.next())
        else {
            bad("expected exactly three tab-separated fields: <target> <sha256> <path>");
        };
        if target.is_empty() {
            bad("empty target triple");
        }
        // The digest rides to the remote host as the deployed-build marker, so a
        // malformed one would be written there and compared against forever.
        if sha256.len() != 64 || !sha256.bytes().all(|b| b.is_ascii_hexdigit()) {
            bad("sha256 must be 64 hex digits");
        }
        let gz = PathBuf::from(gz);
        if !gz.is_file() {
            bad("no such archive");
        }
        out.push((target.to_string(), sha256.to_string(), gz));
    }
    out
}
